# Generated by Django 5.0.4 on 2024-09-21 14:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0016_alter_client_city_alter_client_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="phone",
            field=models.IntegerField(),
        ),
    ]
